<<echo=FALSE, results=hide>>=
## DATA GENERATION
R <- sample(seq(2.0, 2.5, 0.1), 1)
g <- 10

## Resposta
v_ms <- sqrt(5 * g * R)
v <- round(v_ms * 3.6, 1)
@

\usepackage[utf8]{inputenc}

\begin{question}

O inglês Damien Walters, praticante de parkour, conseguiu completar um desafio conhecido como "loop humano". Considere um modelo idealizado em que ele parte do ponto mais baixo de uma trajetória circular vertical de raio \Sexpr{R} m.

Despreze perdas de energia e considere \(g=\Sexpr{g}\) m/s$^2$. Qual é a velocidade mínima de entrada, em km/h, necessária para que ele complete o loop sem perder contato com a trajetória? Arredonde a resposta para uma casa decimal.

\end{question}

\begin{solution}

Para que o praticante apenas mantenha contato com a trajetória no ponto mais alto, a força normal mínima nesse ponto é nula. Assim,

\[
\frac{m v_{\mathrm{topo}}^2}{R}=mg,
\]

de modo que

\[
v_{\mathrm{topo}}^2=gR.
\]

Do ponto mais baixo até o topo, a variação de altura é \(2R\). Pela conservação da energia mecânica,

\[
\frac{1}{2}m v_{\mathrm{entrada}}^2
=
\frac{1}{2}m v_{\mathrm{topo}}^2
+
mg(2R).
\]

Substituindo \(v_{\mathrm{topo}}^2=gR\),

\[
v_{\mathrm{entrada}}^2=5gR.
\]

Logo,

\[
v_{\mathrm{entrada}}
=
\sqrt{5gR}
=
\Sexpr{round(v_ms,2)}\ \mathrm{m/s}
=
\Sexpr{v}\ \mathrm{km/h}.
\]

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{v}}
%% \exname{Q06MCU}
%% \extol{0.1}
